apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      version: green
  template:
    metadata:
      app: bankapp
      version: green
    spec:
      containers:
      - name:bankapp
        image: kaustavsdet/bankapp:green
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: SPRING_DATASOURCE_PASSWORD
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3